name: Mai
version: '1.0.14'
main: me.advait.mai.Mai
api-version: '1.20'
authors: [Advait]
description: Creating an AI-powered world in Minecraft.
commands:
  pathetictest:
    description: Pathetic API test command.
  patheticgroundtest:
    description: Pathetic API ground test command.