on:
  push:
    branches:
      - advait

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build .jar
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build with Maven
        run: mvn clean package
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: target/*.jar  # Only upload JAR files

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Pterodactyl
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
      - name: List current directory
        run: ls -la
      - name: List target directory
        run: ls -la ./target
      - uses: rexlmanu/pterodactyl-upload-action@v2.1
        with:
          panel-host: ${{ secrets.PANEL_HOST }}
          api-key: ${{ secrets.API_KEY }}
          server-id: "c69a0091-a46b-45bd-b7c1-3e305c672c51"
          source: "./Mai-GIT.jar"
          target: "./plugins/"
          restart: true
