on:
  push:
    branches:
      - advait

jobs:

  build-patheticcitizens:
    runs-on: ubuntu-latest
    name: Build PatheticCitizens .jar
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Calculate Commit Info
        id: commit-info
        run: |
          commit_number=$(git rev-list --count HEAD)
          commit_hash=$(git rev-parse --short HEAD)
          echo "COMMIT_NUMBER=$commit_number" >> $GITHUB_ENV
          echo "COMMIT_HASH=$commit_hash" >> $GITHUB_ENV

      - name: Update plugin.yml with Version (PatheticCitizens)
        run: |
          sed -i "s/^version:.*$/version: 1.A.${COMMIT_NUMBER} (${COMMIT_HASH})/" ./PatheticCitizens/src/main/resources/plugin.yml
          echo "Updated version in PatheticCitizens/src/main/resources/plugin.yml"

      - name: Build PatheticCitizens with Maven and push to local repo
       #run: mvn -f ./PatheticCitizens/pom.xml clean package
        run: mvn -f ./PatheticCitizens/pom.xml clean install


      - name: Upload PatheticCitizens Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: patheticcitizens-build-artifact
          path: PatheticCitizens/target/*.jar

  build-mai:
    runs-on: ubuntu-latest
    name: Build Mai .jar
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Calculate Commit Info
        id: commit-info
        run: |
          commit_number=$(git rev-list --count HEAD)
          commit_hash=$(git rev-parse --short HEAD)
          echo "COMMIT_NUMBER=$commit_number" >> $GITHUB_ENV
          echo "COMMIT_HASH=$commit_hash" >> $GITHUB_ENV

      - name: Update plugin.yml with Version (Mai)
        run: |
          sed -i "s/^version:.*$/version: 1.A.${COMMIT_NUMBER} (${COMMIT_HASH})/" ./src/main/resources/plugin.yml
          echo "Updated version in src/main/resources/plugin.yml"

      - name: Build Mai with Maven
        run: mvn clean package

      - name: Upload Mai Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mai-build-artifact
          path: target/*.jar


  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Pterodactyl
    needs: [build-mai, build-patheticcitizens]  # Wait for both build jobs to complete
    steps:
      - uses: actions/checkout@v3

      - name: Download Mai Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: mai-build-artifact

      - name: Download PatheticCitizens Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: patheticcitizens-build-artifact

      - name: List current directory
        run: ls -la

      - name: Deploy Mai to Pterodactyl
        uses: rexlmanu/pterodactyl-upload-action@v2.1
        with:
          panel-host: ${{ secrets.PANEL_HOST }}
          api-key: ${{ secrets.API_KEY }}
          server-id: "c69a0091-a46b-45bd-b7c1-3e305c672c51"
          source: "./Mai-GIT.jar"
          target: "./plugins/"
          restart: false

      - name: Deploy PatheticCitizens to Pterodactyl
        uses: rexlmanu/pterodactyl-upload-action@v2.1
        with:
          panel-host: ${{ secrets.PANEL_HOST }}
          api-key: ${{ secrets.API_KEY }}
          server-id: "c69a0091-a46b-45bd-b7c1-3e305c672c51"
          source: "./PatheticCitizens-GIT.jar"
          target: "./plugins/"
          restart: true